import {
gPlayFabCachedData,
gPFConst,
PlayFab_GetPlayFabID,
PlayFab_ResetPlayFabID,
PlayFab_GetDisplayName,
PlayFab_UserData,
PlayFab_Error,
PlayFab_GetLeaderboardItem,
PlayFab_GetLeaderboardCount,
PlayFab_GetAccountInfoUserName,
PlayFab_LoginWithCustomID,
PlayFab_RegisterUser,
PlayFab_LoginWithEmail,
PlayFab_LoginWithPlayFab,
PlayFab_GetUserData,
PlayFab_UpdateUserData,
PlayFab_UpdatePlayerStatistics,
PlayFab_GetLeaderboard,
PlayFab_AddUsernamePassword,
PlayFab_GetAccountInfo,
PlayFab_LogSDKDetails,
CompileErrorReport
} from "./PlayFab.js";